### ISSUE TITLE
Usable as cli command?

### ISSUE THREAD

**Issue by mesqueeb** [sindresorhus/has-yarn#4]
I love `latest-version` which is usable as CLI command as well through the ported package called `latest-version-cli`.

I often forget if my packages I'm working on use Yarn or NPM and if I could just do a quick check from the terminal with a command `has-yarn` and it returns true or false for that repo, that would be really helpful!

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/has-yarn-cli :)

**Comment by mesqueeb** [comment]
@sindresorhus 
Amazing!!! Thanks so much!
